name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: "registry.digitalocean.com/chaoss-badging"
  IMAGE_NAME: "badging-bot-v2"
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        DO_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
        IMAGE: $(echo $IMAGE_NAME)
        REGISTRY: $(echo $REGISTRY)
        
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        envs: DO_TOKEN, IMAGE, REGISTRY
        script: |
          docker login -u $DO_TOKEN -p $DO_TOKEN registry.digitalocean.com
          docker stop $IMAGE
          docker rm $IMAGE
          docker run -d \
            --restart always \
            --name $IMAGE_NAME \
            $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)
